module.exports.run = async(bot, message, args, dbGuild) => {
  throw Error("this error has been caused")
};

module.exports.help = {
    name: "causeerror",
    aliases: [],
    description: "",
    usage: "",
    cooldown: 0,
    limit: true,
    generated: true
};